name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Compile native extensions
      run: bundle exec rake clobber compile
    - name: Run tests
      run: bundle exec rake spec
    - name: Rubocop
      run: bundle exec rubocop
    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        enable: all
        exclude_check: ./vendor
        force_language: c
        inline_suppression: enable
        other_options: --suppress=missingIncludeSystem
    - name: Send coverage to Code Climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 6ab030bf370ffc2abbf0ba4d70a1c8d9649f6fd1426f48f6d43d5c9eb15f187f
      with:
        coverageLocations: ${{github.workspace}}/coverage/coverage.json:simplecov
        coverageCommand: bundle exec rake coverage
